version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: rootpwd
      POSTGRES_USER: root
    volumes:
      - db_data:/var/lib/mysql
      - ./dev_db_init:/docker-entrypoint-initdb.d:ro
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
