"""create_users_and_conversations

Revision ID: 747eb5bc99eb
Revises: 
Create Date: 2023-12-29 12:01:10.708906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747eb5bc99eb'
down_revision: str|None = None
branch_labels: str|None = None
depends_on: str|None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('private_key', sa.String(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('email_verification_code', sa.String(), nullable=True),
    sa.Column('email_verification_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creator', sa.Uuid(), nullable=False),
    sa.Column('receiver', sa.Uuid(), nullable=True),
    sa.Column('reveiver_public_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['receiver'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sent_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation', sa.Uuid(), nullable=False),
    sa.Column('sender', sa.Uuid(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conversation'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_message')
    op.drop_table('conversation')
    op.drop_table('user_account')
    # ### end Alembic commands ###
