"""Add update and creation date to conversations

Revision ID: 6a60c2887c98
Revises: 38c508973787
Create Date: 2024-01-05 11:48:16.638156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a60c2887c98'
down_revision: str|None = '38c508973787'
branch_labels: str|None = None
depends_on: str|None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_update_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('last_update_date')
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###
