"""Update conversation and message fields

Revision ID: 38c508973787
Revises: 411819536280
Create Date: 2024-01-05 01:30:52.801058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c508973787'
down_revision: str|None = '411819536280'
branch_labels: str|None = None
depends_on: str|None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('reveiver_public_key',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('sent_message', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_message', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('reveiver_public_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
