name: Run the tests and tag releases

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - alpha
      - '[0-9]\.[0-9]\.x'
      - '[0-9]\.x\.x'
      - '[0-9]\.x'

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml

  release-tagging:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: write # Allow the job to write tags on the repo
    steps:
      - uses: actions/checkout@v4
      - name: Run semantic release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ""
