name: Tags CI

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

on:
  push:
    tags:
      - '[0-9]\.[0-9]\.[0-9]*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Calculate the docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            coenern/neutrino
          tags: |
            type=semver,pattern={{ version }}
            type=semver,pattern={{ major }}.{{ minor }}
            type=semver,pattern={{ major }}

      - name: Build and push the image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker_build/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
